import { cn } from '@/lib/utils'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from '@/components/ui/toaster'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn('dark',inter.className)}>
        <main className='min-h-screen'>
          {children}
        </main>
        <Toaster />
      </body>
    </html>
  )
}

interface AuthLayoutProps {
  children: React.ReactNode
}

